# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 013e85500d0172ccc865e71838ba772279ac4b62176aa63bceea9d831bbf9cba7f1ddfa61859f91662749025a3aa2a99dee01fcbd0a50c241f40ef64a3a62c81

test:
  secret_key_base: 984c333813d2cd686c049da86e5e289683bfb48009aedd5e6bc51ac1e934cac64ca44a7d11c578a78ff7e5129db53a5d2d9bcd5d467dd5f8bc0ca2cf36f1b485

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
